# Prefix key
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Source file reload
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# vim pane navigation 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# More natural window splitting, optional
bind | split-window -h
bind - split-window -v

# 1-based window index
set -g base-index 1
setw -g pane-base-index 1
